version: '2.1'
services:
  payara:
    image: payara/server-full:5.2021.7-jdk11
    ports:
      - "8080:8080"
      - "4848:4848"
      - "9009:9009"
    volumes:
      - "./templ_web/target/templ_web-1.0.war:/opt/payara/appserver/glassfish/domains/domain1/autodeploy/java_pf_templ.war"
    environment:
      PAYARA_ARGS: "--debug"